import Head from "next/head";
import LoginPage from "../components/LoginPage";

const Root = () => {
  return (
    <div className="d-flex justify-content-center align-items-center min-vh-100">
      <Head>
        <title>Share-List</title>
        <meta name="share-list" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <LoginPage />
    </div>
  );
};

export default Root;
