import Head from "next/head";
import LoginPage from "../components/LoginPage";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]";

const Root = () => {
  return (
    <div className="d-flex justify-content-center align-items-center min-vh-100">
      <Head>
        <title>Share-List</title>
        <meta name="share-list" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginPage />
    </div>
  );
};

export const getServerSideProps = async (context) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );
  if (session) {
    return {
      redirect: {
        destination: "dashboard",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};

export default Root;
